'use strict'

module.exports = require('neostandard')({
  plugins: {
    functional: require('eslint-plugin-functional'),
    jsdoc: require('eslint-plugin-jsdoc'),
    '@stylistic': require('@stylistic/eslint-plugin')
  },
  rules: {
    '@stylistic/semi': ['error', 'never'],
    '@stylistic/quotes': ['error', 'single'],
    '@stylistic/indent': ['error', 2],
    '@stylistic/object-curly-spacing': ['error', 'always'],
    '@stylistic/array-bracket-spacing': ['error', 'never'],
    '@stylistic/arrow-spacing': 'error',
    '@stylistic/func-call-spacing': ['error', 'never'],
    '@stylistic/computed-property-spacing': ['error', 'never'],
    '@stylistic/space-in-parens': ['error', 'never'],
    '@stylistic/space-infix-ops': 'error',
    '@stylistic/comma-spacing': 'error',
    '@stylistic/comma-style': ['error', 'last'],
    '@stylistic/comma-dangle': ['error', 'ignore'],
    '@stylistic/dot-location': ['error', 'property'],
    '@stylistic/brace-style': ['error', '1tbs'],
    '@stylistic/block-spacing': ['error', 'always'],
    '@stylistic/padded-blocks': ['error', 'never'],
    '@stylistic/eol-last': 'error',
    '@stylistic/no-trailing-spaces': 'error',
    '@stylistic/key-spacing': 'error',
    '@stylistic/keyword-spacing': 'error',
    '@stylistic/new-parens': 'error',
    '@stylistic/no-extra-parens': ['error', 'functions'],
    '@stylistic/template-curly-spacing': ['error', 'never'],
    '@stylistic/yield-star-spacing': ['error', 'both'],
    'no-var': 'error',
    'prefer-const': 'error',
    'no-unused-vars': ['error', { args: 'none' }],
    'no-undef': 'error',
    'no-undef-init': 'error',
    'one-var': ['error', 'never'],
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'no-compare-neg-zero': 'error',
    yoda: ['error', 'never'],
    'use-isnan': 'error',
    'new-cap': 'error',
    'no-array-constructor': 'error',
    'no-object-constructor': 'error',
    'no-new-wrappers': 'error',
    'constructor-super': 'error',
    'no-class-assign': 'error',
    'no-useless-constructor': 'error',
    'no-eval': 'error',
    'no-implied-eval': 'error',
    'no-new-func': 'error',
    'no-caller': 'error',
    'no-global-assign': 'error',
    'no-shadow-restricted-names': 'error',
    'array-callback-return': 'error',
    'no-sparse-arrays': 'error',
    'no-prototype-builtins': 'error',
    'object-shorthand': 'error',
    'no-throw-literal': 'error',
    'no-useless-catch': 'error',
    'prefer-promise-reject-errors': 'error',
    'no-unreachable': 'error',
    'no-fallthrough': 'error',
    'no-regex-spaces': 'error',
    'no-control-regex': 'error',
    'no-invalid-regexp': 'error',
    'prefer-regex-literals': 'error',
    'no-multi-str': 'error',
    'no-param-reassign': 'error',
    'functional/no-let': 'error',
    'no-extra-boolean-cast': 'off'
  }
})
